FROM golang:1.15

RUN go get gitlab.com/vivsoft-platform/k8s-serverless/...

WORKDIR /go/src/gitlab.com/vivsoft-platform/k8s-serverless/svc/link_guardian_service
ADD ./main.go main.go
ADD ./service service

# Fetch dependencies
RUN go get -d -v


RUN CGO_ENABLED=0 GOOS=linux go build -o /link_guardian_service -a -tags netgo -ldflags '-s -w' .

EXPOSE 8080
ENTRYPOINT ["/link_guardian_service"]